### ISSUE TITLE
Feedback for "Response Query"

### ISSUE THREAD

**Issue by fanaugen** [usebruno/bruno-docs-legacy#122]
The last two sections on [this page](https://docs.usebruno.com/scripting/response/response-query#standard-dot-notation) are identical – this doesn’t seem correct.

Or, does this library automatically **filter** when the anonymous function returns a Boolean, and **filter** otherwise?

[[source](https://github.com/usebruno/bruno-docs/blob/a2721aad2333e0650d29c4a9f105be7cdd3e7b4e/src/pages/scripting/response/response-query.mdx?plain=1#L76-L89)]

**Comment by ganesh-bruno** [comment]
@ajaishankar Can you help with the query?

**Comment by ajaishankar** [comment]
@fanaugen @ganesh-bruno Thanks for pointing this out.

Yes, the library filters if the function returns boolean, maps otherwise.

The example for map in the last section is wrong - it should be

```js
res('..items.amount[?]', amt => amt + 10)
```
As in the [tests](https://github.com/usebruno/bruno/blob/main/packages/bruno-query/tests/index.spec.ts#L55) here.

The readme is also [incorrect here](https://github.com/usebruno/bruno/blob/main/packages/bruno-query/readme.md?plain=1#L25)

**Comment by ganesh-bruno** [comment]
Hey @ajaishankar thanks for the review. 

Yes, the library filters when the function returns a boolean, and maps otherwise.

The example for mapping in the last section is incorrect—it should be:

```javascript
res('..items.amount[?]', amt => amt + 10)
```


I'm working on fix.

**Comment by ganesh-bruno** [comment]
Hi @fanaugen @ajaishankar  ,

We’ve added the correct example in the [Response Query Document](https://docs.usebruno.com/scripting/response/response-query). 

Closing this issue now. If you have any other questions or issues, feel free to reach out.
