### ISSUE TITLE
Feedback for “Bruno CLI”

### ISSUE THREAD

**Issue by costiganAPI** [usebruno/bruno-docs-legacy#138]
Does bru run request.bru --reporter-json results.json still work?
 
 I get an error when i try it and i dont see reporter-json amongst the arguments allowed

**Comment by ganesh-bruno** [comment]
Hey @costiganAPI 

Yes, this should work.
Can you share which version of bru cli you are on - `bru --version`?

**Comment by costiganAPI** [comment]
1.22.0

**Comment by ganesh-bruno** [comment]
Hey @costiganAPI,

I tested the `--reporter-json` command on Bruno CLI version 1.22.0 and found that it does not support this command. 
Have you tried upgrading to the latest version of Bruno?  I recommend upgrading to the latest version of Bruno CLI.

If you encounter any issues with the latest version, please feel free to reach out.

**Comment by ganesh-bruno** [comment]
Hey @costiganAPI,

Closing this issue because `--reporter-json` is working on latest [bruno cli version](https://www.npmjs.com/package/@usebruno/cli).

I’ve attached a screenshot of the terminal where the command works with the latest version of Bruno CLI to resolve this issue.

<img width="698" alt="test" src="https://github.com/user-attachments/assets/16a2a673-1741-4511-b4f6-b1351f8ab613">
